name: NeoAnalysis
main: me.neoblade298.neoanalysis.NeoAnalysis
author: [Neoblade298]
depend: [SkillAPI, Quests]
version: 1.0
api-version: 1.16
commands:
   analyze:
      description: This command does its job
      usage: /analyze