 name: NeoConsumables
 version: 1.1
 api-version: 1.14
 description: Written originally by bananapuncher714, edited by Neoblade298
 depend: [NeoSettings, SkillAPI, NeoProfessions]
 author: Neoblade298, bananapuncher714
 main: me.Neoblade298.NeoConsumables.Consumables
 commands:
   cons:
     description: Does its job
     usage: /cons