# Add delays by adding $delay$ to the start of the line, with delay being how long to wait in ticks
# Make sure there's a space after $delay$!
# 20 ticks = 1 second
# Add commands by adding a / to the front of the line
# Conversations are played sequentially
conversations:
  ExampleConv:
  - "Hello there"
  - "$60$ This is a test conversation"
  - "/mythicmobs items give -s <player> 2019Treasure1" # runs at the same time as the line above
  - "$100$ /say hi" # Runs 2 after the above line, 3 seconds after the first line