name: NeoConversations
main: me.neoblade298.neoconversations.Conversations
author: [Neoblade298]
version: 1.0
api-version: 1.16
commands:
   conv:
      description: Does stuff
      usage: /conv