name: NeoCore
main: me.neoblade298.neocore.NeoCore
author: [Neoblade298]
version: 1.0
api-version: 1.16
commands:
   core:
      description: NeoCore command
      usage: /core
   bcore:
      description: NeoCore bungee command
      usage: /bcore
   help:
      description: Base help command
      usage: /help
   features:
      description: Base features command
      usage: /features
   commands:
      description: Base commands command
      usage: /commands