name: NeoBossInstances
author: Neoblade298
main: me.neoblade298.neobossinstances.Main
api-version: 1.16
version: 1.0
loadbefore: [SkillAPI]
depend: [LuckPerms, NeoSettings]
softdepend: [Multiverse-Core, MythicMobs]
commands:
  boss:
    description: Does its job
    usage: /boss