name: NeoProfessions
author: Neoblade298
main: me.Neoblade298.NeoProfessions.Professions
version: 1.0
api-version: 1.16
depend: [MythicMobs, SkillAPI, NeoGear, Vault, mcMMO]
softdepend: [NeoBossRelics, NeoMythicExtension]
commands:
  value:
    description: Value command
    usage: /value
  prof:
    description: Admin commands
    usage: /prof [args]