name: NeoMythicExtension
author: Neoblade298
main: me.neoblade298.neomythicextension.Main
version: 1.00
depend: [MythicMobs]
softdepend: [NeoBossInstances, NeoResearch, NeoSettings]
api-version: 1.16
commands:
  nme:
    description: Does its job
    usage: /nme