name: NeoQuests
main: me.neoblade298.neoquests.NeoQuests
author: [Neoblade298]
depend: [Citizens, NeoCore, Multiverse-Core]
softdepend: [SkillAPI]
version: 1.0
api-version: 1.18
commands:
   quest:
      description: Quest command
      usage: /quest
      aliases: q
   quests:
      description: Quests command
      usage: /quests
   navigation:
      description: Navigation command
      usage: /navigation
      aliases: nav
   adminnavigation:
      description: Admin Navigation command
      usage: /adminnavigation
      aliases: [anav, anavigation]