name: NeoQuests
main: me.neoblade298.neoquests.NeoQuests
author: [Neoblade298]
depend: [Citizens]
softdepend: [SkillAPI]
version: 1.0
api-version: 1.18
commands:
   quests:
      description: This command allows you to disenchant item in hand
      usage: /disenchant
      permission: disenchant.true