name: NeoQuests
main: me.neoblade298.neoquests.NeoQuests
author: [Neoblade298]
depend: [Citizens, NeoCore]
softdepend: [SkillAPI]
version: 1.0
api-version: 1.18
commands:
   quests:
      description: Quest command
      usage: /quests