name: NeoQuests
main: me.neoblade298.neoquests.NeoQuests
author: [Neoblade298]
depend: [Citizens, NeoCore, Multiverse-Core]
softdepend: [SkillAPI]
version: 1.0
api-version: 1.18
commands:
   nquest:
      description: Quest command
      usage: /nquest
      aliases: nq
   nquests:
      description: Quests command
      usage: /nquests
   navigation:
      description: Navigation command
      usage: /navigation
      aliases: nav
   adminnavigation:
      description: Admin Navigation command
      usage: /adminnavigation
      aliases: [anav, anavigation]