# Valid vote services
websites:
  - MCSL
  - BestMinecraftServers
  - Blablabla

# number of votes before a streak rolls over to 0
streak-vote-limit: 125

# number of days without votes before a streak resets
streak-reset-leniency: 2