name: NeoSettings
main: me.neoblade298.neosettings.NeoSettings
author: [Neoblade298]
depend: [SkillAPI, NeoCore]
version: 1.0
api-version: 1.16
commands:
   playerdata:
      description: Main command
      usage: /playerdata
      aliases: pd